---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: /src/k8s.io/helm

steps:
- name: build
  pull: default
  image: golang:1.10
  commands:
  - ./.circleci/bootstrap.sh
  - make test-unit
  - make build-cross APP=helm
  - make build-cross APP=tiller
  - make build-cross APP=rudder
  - mv ./_dist/linux-arm64/helm ./_dist/linux-arm64/helm-arm64
  - mv ./_dist/linux-arm64/tiller ./_dist/linux-arm64/tiller-arm64
  - mv ./_dist/linux-arm64/rudder ./_dist/linux-arm64/rudder-arm64
  - mv ./_dist/linux-arm/helm ./_dist/linux-arm/helm-arm
  - mv ./_dist/linux-arm/tiller ./_dist/linux-arm/tiller-arm
  - mv ./_dist/linux-arm/rudder ./_dist/linux-arm/rudder-arm
  environment:
    PROJECT_NAME: "\"kubernetes-helm\""
    TARGETS: linux/amd64 linux/arm64 linux/arm

- name: publish-github-rc
  pull: default
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "bin/*"
    - _dist/linux-amd64/*
    - _dist/linux-arm64/*
    - _dist/linux-arm/*
    prerelease: true
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - tag
    ref:
    - "refs/tags/*rc*"
    - refs/heads/rancher

- name: github_binary_release
  pull: default
  image: plugins/github-release
  settings:
    checksum:
    - sha256
    files:
    - "bin/*"
    - _dist/linux-amd64/*
    - _dist/linux-arm64/*
    - _dist/linux-arm/*
    api_key:
      from_secret: github_token
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - tag
    ref:
      exclude:
      - "refs/tags/*rc*"
